function [ points ] = createSquarePoints( center, radius )
%CREATESQUAREPOINTS Generate plottable square w/ 4 corners.
points = [center + [-radius -radius];...
          center + [-radius  radius];...
          center + [ radius  radius];...
          center + [ radius -radius]];
points(end+1,:) = points(1,:);
end
